### ISSUE TITLE
Clamav Vulnerability 

### ISSUE THREAD

**Issue by robaca** [ajilach/clamav-rest#11]
According to https://blog.clamav.net/2023/02/clamav-01038-01052-and-101-patch.html, there is a critical vulnerability in the ClamAV version available as part of Alpine 3.16. 

Please provide a new fixed version of the docker image, maybe based on Alpine 3.17.

**Comment by rhermanek** [comment]
Thanks for pointing it out. The new release is published with Alpine 3.17
