### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by raziel057** [ajilach/clamav-rest#13]
Hello,

It would be nice to allow the configuration / check of an ACCESS_TOKEN or BASIC Authentication to secure the access to the service.

Do you consider to add such option?

Thanks

**Comment by arizon-dread** [comment]
Hi, 

That is out of scope for this project, I would suggest putting an NGINX or Apache in front of the clamav-rest container to handle basic authentication, or a project such as [this oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) in front of it.

It is not possible for this small project to maintain such a feature inside the project and as stated in the beginning, it's out of scope.

**Comment by arizon-dread** [comment]
Hi, 

That is out of scope for this project, I would suggest putting an NGINX or Apache in front of the clamav-rest container to handle basic authentication, or a project such as [this oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) in front of it.

It is not possible for this small project to maintain such a feature inside the project and as stated in the beginning, it's out of scope.

**Comment by arizon-dread** [comment]
Hi, 

That is out of scope for this project, I would suggest putting an NGINX or Apache in front of the clamav-rest container to handle basic authentication, or a project such as [this oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) in front of it.

It is not possible for this small project to maintain such a feature inside the project and as stated in the beginning, it's out of scope.
