### ISSUE TITLE
HTTP/2 clear (h2c) support

### ISSUE THREAD

**Issue by umut-saribiyik-acc** [ajilach/clamav-rest#17]
Hi

is it possible that you can implement HTTP/2 clear (h2c) support for the clam-av rest? I deployed your Docker image in Google cloud run and hit the 32 MB file size limitation. That means you can't scan files for threads which are bigger than 32 MB. Regarding to the Cloud Run documentation, there is no file size limitation for HTTP/2.

A possible workaround could be to setup a reverse proxy (e.g nginx) in front of your API which can handle HTTP/2.

Sources:
https://cloud.google.com/run/quotas
https://cloud.google.com/run/docs/configuring/http2

Thanks
Umut.

**Comment by rhermanek** [comment]
Hi Umut

I currently cannot reproduce your issue. From Go 1.6 (as far as i remember correctly) http2 is standard for the net/http library/package.
I just tested by sending a 90MB file through http and https and both worked. You must however overwrite the values:
```
ENV MAX_SCAN_SIZE=100M
ENV MAX_FILE_SIZE=100M
```
To allow the application to accept bigger files. 

Did you pull the latest image?

BR

**Comment by rhermanek** [comment]
Ah ok now I get it :D 
Hmm I can take a look at it and see if I find an easy way to implement that.

**Comment by rhermanek** [comment]
Hey @umut-saribiyik-acc 
Have you tried configuring GCR to use the TLS port instead of the http port? I think that way the http library is forced to run in http2 mode.

**Comment by umut-saribiyik-acc** [comment]
Hi @rhermanek 

Yes, I tried also the TLS Port (9443) and it doesn't worked. Regarding to the GCR documentation, the Docker Service Endpoint must be HTTP/2c (h2c) which is not TLS / SSL. 
HTTP/2c (h2c) is without SSL. You don't need certificates for it.

Google Cloud Run documentation abstract: https://cloud.google.com/run/docs/configuring/http2

![image](https://user-images.githubusercontent.com/127969643/226615181-0d21d7a5-664e-463a-8082-bab423998423.png)

**Comment by umut-saribiyik-acc** [comment]
Hello @rhermanek 

No problem and thanks a lot for your time :)
I will try to modify your image by putting a nginx in front of your GO REST API.
