### ISSUE TITLE
Fail update, and fail create tmp file

### ISSUE THREAD

**Issue by Namtv2312** [ajilach/clamav-rest#31]
I got an error with: 
![image](https://github.com/ajilach/clamav-rest/assets/60953789/9c612374-2857-4081-a9b1-6ea2eef34a49)
![image](https://github.com/ajilach/clamav-rest/assets/60953789/2d26c561-0131-431f-a40a-f640e7b8e6a7)
, 
How can you help me,

**Comment by arizon-dread** [comment]
Please try the latest version and reopen the issue if it persists with more information on the platform where you're getting the issue.
