### ISSUE TITLE
ClamAV vulnerability

### ISSUE THREAD

**Issue by Marsup** [ajilach/clamav-rest#40]
Hi!

According to https://blog.clamav.net/2023/11/clamav-130-122-105-released.html, clamav 1.1 is not (and will not) be patched against this security issue, it appears that alpine 3.19 has a patched version (1.2.2-r0). #35 already does the version bump, I did some quick tests and didn't notice any regression. Could this PR be merged?

**Comment by kristijonasb** [comment]
I support this request #35 
@davosian - can this be merged?

**Comment by davosian** [comment]
finally merged, thanks @Marsup
