### ISSUE TITLE
Anticipate bump of Clamav to 1.3.1-r0 that will come with next Alpine release 3.21 in November

### ISSUE THREAD

**Issue by borrelm** [ajilach/clamav-rest#53]
Hello ! 

Based on their [release cycle](https://alpinelinux.org/releases/), Alpine will release the edge branch into 3.21 in November.
[Edge branch bump clamav from 1.2.2-r0 to 1.3.1-r0](https://pkgs.alpinelinux.org/packages?name=clamav&branch=edge&repo=community&arch=&maintainer=)

I don't have the skills to do it myself, but It would be nice if someone could test there is no regression in clamav-rest with clamav 1.3.1-r0 before then :)

**Comment by arizon-dread** [comment]
After bumping to alpine 3.21 (it initially broke the build), it installs clamav 1.4.1, have successfully tested the functionality, and the PR #62 produces a functioning version (that builds) once reviewed and merged. Although, the security issue if you send multiple files to the `/scan` endpoint and the first file is clean, a 200 OK will always be returned, regardless of the status of the files following the first, is still there. #50 fixes that but is still awaiting review by @davosian.
