### ISSUE TITLE
Client sent an HTTP request to an HTTPS server

### ISSUE THREAD

**Issue by gvoden** [ajilach/clamav-rest#55]
I am getting this error when running curl against the service which is running on EKS: 

Client sent an HTTP request to an HTTPS server.

I have a valid SSL certificate installed on a load balancer.

**Comment by arizon-dread** [comment]
What does your curl request look like? Can you post it? 

This error sounds like your curl is specifying http://my-eks.instance.com:443

So the scheme is http but the port is https.

**Comment by gvoden** [comment]
Actually I fixed my issue. The ingress proxy was sending the traffic to the https port 9443 but using a http call since we are offloading SSL onto the load balancer. Reconfigured the ingress to forward https traffic to port 9000 instead.
