### ISSUE TITLE
Scanned filename in clamd logs

### ISSUE THREAD

**Issue by gkout** [ajilach/clamav-rest#8]
Currently the clamd logs the following information with the filename missing:

Thu Oct 27 10:01:43 2022 -> instream(127.0.0.1@42164): Eicar-Signature FOUND

It would be good to add a feature to pass the name of the file that is submitted to the api, to clamav logs. 
Not sure if it would make more sense to log the files on the http server level.

Thx!!!

**Comment by rhermanek** [comment]
Hi there

The stdout does currently log the filename but as you correctly said it does not get written to the clamav logfile.
We can take a look at implementing this feature soon.

**Comment by rhermanek** [comment]
Hi @gkout 
I've just updated the container to log to /var/log/clamav/clamav.log. There you will find the filenames! The latest image in DockerHub should already contain the changes. Feel free to take a look at the changes for any Feedback.

BR
Robin
